### ISSUE TITLE
DNS Update Page

### ISSUE THREAD

**Issue by larsenv** [WiiLink24/web#101]
@Humanoidear can you make a notice on the website telling people about the new DNS in a place where everyone can see it? I bet there's a lot of people which aren't aware of it yet and a Wii Mail announcement would be good as well, simply let everyone know

**Comment by NecroNovaVGitHub** [comment]
Afaik _**this is being worked on**_, please stop closing and reopen your issues/pull requests to get our attention

**Comment by Humanoidear** [comment]
This has now been added to the main site
