### ISSUE TITLE
Everybody Votes Channel RiiConnect24 Results Lead to Dead Page

### ISSUE THREAD

**Issue by devonkel4** [WiiLink24/web#111]
Under [https://www.wiilink24.com/extras/vote](https://www.wiilink24.com/extras/vote), the RiiConnect24 link leads to [https://vt.wii.rc24.xyz/](https://vt.wii.rc24.xyz/). This appears to be a dead page as it has expired certificates, and bypassing warnings leads to a dead page with a generic Invalid Request.

**Comment by kouacc** [comment]
Hello, a new website is currently being made. The old URL will redirect to the new one when we release it.
