### ISSUE TITLE
Diego's image is broken

### ISSUE THREAD

**Issue by korbough** [WiiLink24/web#41]
![image](https://github.com/WiiLink24/web/assets/47117026/9a559d4b-84ad-4ad7-9a10-9158af8e850e)

**Comment by korbough** [comment]
This is apparently because the jpg lacks any data, being 0 B big.

**Comment by NecroNovaVGitHub** [comment]
This issue will be fixed in a major update soon. For now, this issue will have to be closed due to redundancy.

**Comment by korbough** [comment]
Ok!
