### ISSUE TITLE
Discord Server Embed Not Functional

### ISSUE THREAD

**Issue by ren-makes-things** [WiiLink24/web#79]
The Discord server embed on the page is not functional, you aren't able to scroll or press Join. The Twitter embed however works fine

Tested on Chromium 123.0.6312.59 and Safari 17.4 

See attached videos

https://github.com/WiiLink24/web/assets/96893300/fe565ead-c92f-4ed8-ba83-521ccef7db13
https://github.com/WiiLink24/web/assets/96893300/6efdab1e-276b-44dc-a345-37c43c41b9a5

**Comment by Humanoidear** [comment]
A wrong z-index value was causing it to be unresponsive, it's been fixed now!
