### ISSUE TITLE
[ENHANCEMENT] Make the status texts already translated and then the json only have the status type.

### ISSUE THREAD

**Issue by Hassunaama** [WiiLink24/web#85]
Since mainly only the English (US) version status page is updated frequently and the other translated pages are constantly going out of date I think a system like this would help.

<hr>

<b>So, my idea is that there is 1 "status.json" file in the root of the json folder or somewhere like that, that has all the status info for all the channels like this:

![image](https://github.com/WiiLink24/web/assets/64845406/26922f8e-7225-4b29-afb3-cef04060cbe9)
![image](https://github.com/WiiLink24/web/assets/64845406/feff13f9-a6e1-4f02-ac83-2ae8af320af3)

And then there would be like a status text section in the locales jsons where you would input the default texts.

This would make all the status texts update at the same time and also make the texts at least half translated</b>

**Comment by Humanoidear** [comment]
I'm afraid this wouldn't be possible because the status text can really be anything, not just premade strings :/

**Comment by Hassunaama** [comment]
well yeah but the status pages running out of date is still an issue

**Comment by Hassunaama** [comment]
![image](https://github.com/WiiLink24/web/assets/64845406/9e0f3029-93fa-4235-96b4-db7dfa62e613)
![image](https://github.com/WiiLink24/web/assets/64845406/1fc7cad2-aeba-4276-a50d-fc09bf4fa52e)
![image](https://github.com/WiiLink24/web/assets/64845406/80b1f2db-664c-49cc-9278-51044fe25f03)
